apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mlbh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mlbh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mlbh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mlbh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mlbh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mohd-tenant/rhtap-demo-app/hacbs-test-project-mlbh@sha256:bc5d628c8400870d70c1dd0dafb8ce5f37a0440114164d1ceff1658051cf45dc
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
