apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mlbh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mohd-tenant/rhtap-demo-app/hacbs-test-project-mlbh@sha256:1bd0c207ff8769a4691ecb59a4d4629a56a52885afaec121d593ce05b0e2792e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
